# encoding: UTF-8
---
driver:
  name: vagrant
  customize:
    memory: 512

provisioner:
  name: chef_zero
  require_chef_omnibus: true

platforms:
  - name: centos-6
  - name: centos-7

suites:
  - name: default
    run_list:
      - recipe[test_fixtures::devreporter]
      - recipe[odsee::install]
    attributes:

  - name: example
    run_list:
      - recipe[test_fixtures::devreporter]
      - recipe[odsee::example]
    attributes:
